version: "3.8"
services:
  elasticsearch:
    image: elasticsearch:8.17.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.security.http.ssl.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
  logstash:
    image: logstash:8.17.2
    volumes:
      - ./config:/usr/share/logstash/pipeline
    ports:
      - "5044:5044"
      - "9600:9600"
  kibana:
    image: kibana:8.17.2
    ports:
      - "5601:5601"
volumes:
  elasticsearch-data:
